spring:
  application:
    name: pelican
server:
  port: ${PORT:8080}
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
feign:
  hystrix:
    enabled: true